lvandeve/lodepng

pngdetail.cpp

Printing un/compressed size info was switched around in pngdetail.

pngdetail size print fix

---

lodepng.cpp
lodepng.h

Before this change, encode() would return 0 whether or not the output
file was created.  There was no way for a caller to know when the
file could not be created (e.g. due to a non-existent parent directory).
Changed save_file() to return error 79 if it cannot open output file.
encode() checks return code from save_file() and passes any error value
back to the caller.

encode() returns error code if save_file() cannot open output file.

---

pngdetail.cpp

VS2015 can't find std::min/max without additional header.

Fix VS2015 compilation of pngdetail.

---

lodepng_util.cpp

Fix crash on PNG files with a single column of pixels.

---

lodepng.cpp

When writing an uncompressed PNG, deflateDynamic erroneously indexed a newly allocated block of datasize length using the datapos offset. This would crash anytime datapos > 0.

Fixed crash on uncompressed PNG files.

---

lodepng.cpp

The return value of huffmanDecodeSymbol is stored in code_d not code_ll,
code_ll is between 257 and 285 here.

Fix wrong error code if huffmanDecodeSymbol fail

---

lodepng.cpp

Resolved issue #24, which was only partially resolved by pull request #34.

Resolved issue #24

---

lodepng.cpp

`buffer` is already declared as `const unsigned char*`, which can be
transparently accepted by `fwrite()`. Casting it to `char*` here just
makes compilers complain about "discarding cv-qualifiers", so this
commit removes that cast.

fix compiler warnings about const-breaking cast

---

lodepng.cpp

```
../third_party/lodepng/lodepng.cpp:4055:45: warning: cast from 'const unsigned char *' to 'unsigned char *' drops const qualifier [-Wcast-qual]
(unsigned char*)(&data[string2_begin]),
^
../third_party/lodepng/lodepng.cpp:4135:47: warning: cast from 'const unsigned char *' to 'unsigned char *' drops const qualifier [-Wcast-qual]
(unsigned char*)(&data[begin]),
^
../third_party/lodepng/lodepng.cpp:4248:43: warning: cast from 'const unsigned char *' to 'unsigned char *' drops const qualifier [-Wcast-qual]
(unsigned char*)(&data[string2_begin]),
^
../third_party/lodepng/lodepng.cpp:4778:41: warning: cast from 'const char *' to 'unsigned char *' drops const qualifier [-Wcast-qual]
(unsigned char*)textstring, textsize, zlibsettings);
^
../third_party/lodepng/lodepng.cpp:4811:43: warning: …
```

Fix warnings on const cast correctness

---

lodepng.cpp

Without a fixed underlying type, the range of LodePNGColorType is [0, 8) since all the values can be represented by 3 bits. This means that the cast from an arbitrary unsigned char to a LodePNGColorType in lodepng_inspect() is not valid for values not in that range. To fix this we check that the colour type is valid before casting it to a LodePNGColorType so that all LodePNGColorType instances are valid.

Fix undefined behaviour when casting an out of range value to an enum

---

lodepng.cpp

should fix https://github.com/lvandeve/lodepng/issues/91

add (unsigned) cast to each byte in lodepng_read32bitInt()

---

lodepng.cpp

they aren't declared in lodepng.h and are private to lodepng.c

make lodepng_read32bitInt() and lodepng_get_raw_size_lct() static.

---

lodepng.cpp

HuffmanTree_cleanup: change initializer of mask to a real constant constant

---

lodepng.cpp
lodepng_unittest.cpp

Gray is only less overhead than palette when there's no alpha channel.
Noticed a regression on gray alpha pngs when testing latest zopfli, this is introduced in https://github.com/lvandeve/lodepng/commit/1d1b55c071591d9537bf5adf67af8d473af6beb8

Allow palette for gray alpha.

---

lodepng.h

The addition of a virtual destructor to LodePNGState when compiled as C++ causes a vptr to be added at the start of the struct. This results in the members of the struct changing their offset depending on whether they're seen from C or C++ code. Internally the LodePNGState struct is never deleted (as to invoke the virtual destructor) and has no virtual methods called on it so it doesn't need to be virtual. Hence fix the ABI incompatibility by removing the virtual destructor.
A demonstration of the problem using Compiler Explorer: https://godbolt.org/z/UJHBLf. Note that when compiled as C++ the offset of `error` moves 8B further into the struct due to the pointer inserted at the beginning.
Dropping the virtual destructor for LodePNGState also allowed the dropping of the virtual keyword …

Fix ABI incompatibility when calling a C++ compiled lodepng.cpp from C code or vice versa

---

lodepng.cpp

previously, it ignored any gcc with `__GNUC_MINOR__` == 0.

fix LODEPNG_RESTRICT for gcc

---

lodepng.h

`lodepng_auto_choose_color` definition was removed on 430268baa882a707c36b356402b94ab14dc08b69.
Removing orphan prototype.

Remove lodepng_auto_choose_color prototype

---

examples/example_bmp2png.cpp
examples/example_encode.c
examples/example_encode.cpp
examples/example_png2bmp.cpp

1. Two occurrences of "this samples" in ``example_encode.c`` and ``example_encode.cpp`` in a warning about overwriting files. This warning applies to all the examples, and should thus be "these samples".
2. Two typos of "provide" and one swap of BMP/PNG, as noted in https://github.com/lvandeve/lodepng/issues/132

Typos in example programs

---

lodepng.cpp

If you build an executable using lodepng with `-g -Og -fsanitize=address,undefined -fsanitize-no-recover=all` in CFLAGS and try to load [this image file](https://github.com/hpjansson/chafa/blob/master/tests/data/bad/lodepng-zero-length-literal.png), the program will abort with the following output:
```
lodepng.c:1370:28: runtime error: applying zero offset to null pointer
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior lodepng.c:1370:28
```
The fix is to check for a NULL pointer before trying to do calculations with it.

Fix undefined behavior found by UBSan fuzzing

---

lodepng.cpp

If l == 0 we don't need to load symbol and call reverseBits.
However if we do, symbol is uninitialized and function call
with uninitialized argument and behavior is undefined.

Continue early to avoid uninitialized value

---

lodepng.cpp

This fixes a warning when building with -Wcast-qual.

Preserve const qualifier
